Optionally wrap the APIClient actions inside a Response class (#37)
deliveroo/routemaster-drain pull request #37
Opened 2017-03-23 15:19 UTC by angetheo

## Why

The `#post`, `#patch` and `#delete` methods return a `Faraday::Response` since 2.4.0 even after wrapping the HTTP request inside the `with_response` block. This causes some specs on `orderweb` to fail, as it was expecting a `HateoasResponse` back from those actions.

## What

Wrap the methods inside `@response_class` if provided by using `_wrapped_response` method.

### Why the #delete method needs to be wrapped?

IMO whoever uses actions on a `RestResource` should always return a `HateoasResponse`, regardless of the specific action. As correctly stated in the comment, the `delete` method should return an empty body and a `204`, but as we are still inside a `hateoas`-like communication between services, we shouldn't expect a different class if we call `delete`.

2017-03-24 09:17 UTC, gbonfant commented
👍

2017-03-24 09:17 UTC, levriero approved these changes

2017-03-24 14:41 UTC, mezis requested changes

2017-03-24 14:41 UTC, mezis commented on lib/routemaster/resources/rest_resource.rb
> +        @client.with_response(Responses::HateoasResponse) do
I think we never want to wrap the response to `DELETE` because our API guidelines say there should never be a body :)

(ie. the comment was valid)

2017-03-24 14:41 UTC, mezis commented on lib/routemaster/api_client.rb
> +      _wrapped_response _request(
If you really want to expose the same _class_ when deleting (honestly, I still don't see why) — then can you guarantee the response will be empty?

Maybe pass an empty body to the rapper, or soemthing?

2017-03-24 14:42 UTC, mezis commented on CHANGELOG.md
> +- Optionally wrap the APIClient actions inside a Response class (#37)
Well, it was untested behaviour so... not really a bug fix ;)

2017-03-27 09:37 UTC, angetheo commented on lib/routemaster/resources/rest_resource.rb
> +        @client.with_response(Responses::HateoasResponse) do
I see, for me it was mostly about consistently getting the same response, but as we delegate most of the methods to `Faraday::Response` (including the response body) I really don't mind going in either way (it was just a proposal anyway).

I'll change it back to be a pure faraday response 👍

2017-03-27 09:50 UTC, angetheo commented on CHANGELOG.md
> +- Optionally wrap the APIClient actions inside a Response class (#37)
Ha, well that's technically true 💅

2017-03-27 13:57 UTC, mezis approved these changes

2017-03-27 13:58 UTC, merged