Remove unsafe memoization of auth config
deliveroo/routemaster-drain pull request #65
Opened 2017-09-15 10:01 UTC by FriedSock

There seems to be a threading issue with this memoization that
causes the cache auth to be set to an empty Hashie::Rash. I am
not sure if this can be solved by replacing the store with a
simple hash, or other means, but the quickest way to restore
thread safety is to remove the memoization.

2017-09-15 10:10 UTC, mvalipour commented
☝️ @tompave-roo

2017-09-15 11:43 UTC, tompave-roo requested changes
This is a very expensive operation to execute over and over _for each `APIClient` request_.

Have you considered instead:
* wrapping it in a mutex
* checking if the `Hashie::Rash` is empty, and regenerating it if it is?

2017-09-15 11:57 UTC, mvalipour commented
@tompave-roo Out of curiosity, what's the reason behind using `Hashie::Rash`?
Why don't we just use a normal hash? It's surely much more reliable and more performant.

It looks like the only `2` times `cache_auth` is called in the entire code base of deliveroo is [here](https://github.com/deliveroo/orderweb/blob/b1f632bd86d386c46cda417732a71b565991fe56/app/services/drivers/pay/accounting_service.rb#L255) and [here](https://github.com/deliveroo/routemaster-drain/blob/e997b15fa47fc0f09296e4e7ff9934da3c37e954/lib/routemaster/api_client.rb#L145) -- both of which do a simple fetch.

2017-09-15 12:22 UTC, FriedSock commented
@tompave an expensive operation is better than an incorrect one surely? as I said in the description, I don't want to spend time investigating how to replace the existing memoization with a thread safe one; thinking it is better to remove it than leave the behaviour in a broken state.

2017-09-20 17:24 UTC, tompave-roo approved these changes

2017-09-20 17:30 UTC, merged

2017-12-18 10:47 UTC, Antti commented
OK, I looked deeper into this problem and here's what I found:

[Here](https://github.com/intridea/hashie/blob/32514df06550e21dc47d5c989ff6a90ef0c9b9fa/lib/hashie/rash.rb#L139) there is a bug in `Hashie::Rash`, which causes a hash(Rash) to lose items randomly:

It replaces content of the `@regexes` with the new array, based on the count table, which is initially empty and then is filled up with the values after a lookup.
So if there was no lookup for a given regex in 500 lookup cycles, the regex will not get into the table and will be lost after the next "optimisation".

This was causing problems in the `routemaster-drain` gem in the version below `3.0.3`, where the auth keys were disappearing suddenly.

2017-12-18 10:55 UTC, Antti commented
Here's a PR: https://github.com/intridea/hashie/pull/430

2017-12-19 20:46 UTC, michaelherold commented
I just released v3.5.7 of Hashie, which includes @Antti's fix for Rash. Please let us know if any other upstream bugs are causing problems for you!